version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
